name: 'Repo Keeper'
description: 'Runs Repo Keeper'
author: 'OLeonardoRodrigues'

branding:
  icon: 'sliders'
  color: 'green'

inputs:
  github-pat:
    description: 'GitHub PAT.'
    required: true

  config-file:
    description: 'Configuration File Name or Path.'
    required: false
    default: '.repo-keeper'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/oleonardorodrigues/repo-keeper:latest'
  env:
    GH_PAT: ${{ inputs.github-pat }}
    CONFIG_FILE: ${{ inputs.config-file }}
