name: 'LRO Repo Scaffolder'
description: 'Runs Repository Scaffolder for GitHub.'

inputs:
  github-pat:
    description: 'GitHub PAT.'
    required: true

runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - '-e GH_PAT=${{ inputs.github-pat }}'
