name: "Run Repo Keeper"

on: [push]

jobs:
  keypr:
    name: "Run Repo Keeper"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: LRO Repo Scaffolder
        uses: fr-platform/keypr@v0.2.0
        with:
          github-pat: ${{ secrets.PAT }}
